Manifest V3
aboutsource/trektor pull request #17
Opened 2024-01-16 15:17 UTC by wendelin-as

### Problem:

- Chromium unterstützt background scripts nicht mehr, sondern nur service workers
- Firefox bleibt bei background scripts und unterstützt keine service workers
- In Chromium kann nur ein service worker verwendet werden
- Das background script kann nicht in ein content script umgewandelt werden, da Firefox dann die CSP der entsprechenden Website verwendet und die API requests blockiert werden

### Hier umgesetzte Lösung: 
trecktor.js und das background script werden in eine Datei zusammengeführt. Diese wird im Manifest als background script und als service worker eingebunden. Firefox ignoriert dabei den nicht unterstützten service worker; Chromium ab Version 121 ignoriert das background script - in früheren Chromium-Versionen schlägt das Laden wegen des background scripts jedoch leider fehl.

2024-01-22 10:18 UTC, ushi-as requested changes

2024-01-22 10:18 UTC, ushi-as commented on manifest.json
>          "vendor/browser-polyfill.js",
Kann das auch weg?

2024-01-22 10:18 UTC, ushi-as commented on scripts/background.js
> +  }
Warum static? Gehts vllt auch sowas:

```js
class Background {
  private trektor;

  constructor (trektor) {
    this.trektor = trektor;
  }

  run() {
    trektor.runtime.onMessage.addListener(...);
  }

  private x() {
    this.trektor.doThings();
  }
}
```

und beim aufruf wäre es dann: `new Background(getTrektor()).run()`

2024-01-22 10:18 UTC, ushi-as commented on scripts/content_script.js
> +      console.log("start tracking card")
kann am ende alles raus.

2024-01-22 10:18 UTC, ushi-as commented on scripts/content_script.js
> +        action: 'track',
konsistent wäre schöner.

2024-01-22 10:18 UTC, ushi-as commented on scripts/content_script.js
> +      throw err;
debug..

2024-01-22 10:18 UTC, ushi-as commented on scripts/trektor.js
> +  }
```suggestion
    togglGateway: new TogglGateway(browser.storage.local),
    browser: browser,
  }
```

2024-01-22 10:18 UTC, ushi-as commented on scripts/background.js
> +    browser.runtime.onMessage.addListener(async (msg) => {
```suggestion
    trektor.browser.runtime.onMessage.addListener(async (msg) => {
```

2024-01-22 10:18 UTC, ushi-as commented on scripts/background.js
> +
```suggestion
```

2024-01-22 11:13 UTC, wendelin-as commented on manifest.json
>          "vendor/browser-polyfill.js",
ist jetzt weg, dafür haben wir im content script jetzt auch noch mal 
```js
if (typeof browser == "undefined") {
  globalThis.browser = chrome
}
```

2024-01-23 08:54 UTC, ushi-as commented on manifest.json
>          "vendor/browser-polyfill.js",
Mist. Spricht was dagegen `trektor.js` mit im content script zu includen?

2024-01-23 13:59 UTC, ushi-as requested changes
Kleinkram noch, dann is super.

2024-01-23 13:59 UTC, ushi-as commented on manifest.json
> +        "scripts/trektor.js"
Hier die Reihenfolge noch aufräumen?

```suggestion
        "scripts/trektor.js",
        "scripts/content_script.js"
```

2024-01-23 13:59 UTC, ushi-as commented on scripts/chromium.js
> +importScripts('background.js', 'trektor.js');
```suggestion
importScripts('trektor.js', 'background.js');
```

2024-01-24 09:41 UTC, ushi-as approved these changes

2024-01-24 09:42 UTC, merged